version: '3.8'

services:
  csharp-sample:
    container_name: csharp
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 9001:9001
